
inicio
	inteiro x, y
      escrever "Informe o valor de X:"
      ler x
      escrever "Informe o valor de y"
      ler y
      Se x > y entao
          escrever "O Valor informado de X " , x , " é maior"
      senao
          se x < y entao
              escrever "O valor informado de Y ", y, " é maior"
          senao
              escrever "Ambos numeros são iguais X ", x , " e Y " , y
          fimse
      fimse
        
fim
