inicio
    variavel inteiro idade
    escrever "Informe a idade :"
    ler idade
    escolhe idade
        caso 1,2,3,4:
            escrever "Inválido"
        caso 5, 6, 7:
            escrever "Infantil A"
        caso 8, 9, 10, 11:
            escrever "Infantil B"
        caso 12, 13:
            escrever "Juvenil A"
        caso 14, 15, 16, 17:
            escrever "Juvenil B"
   defeito :
       escrever "Adulto"
   fimescolhe    
    
	
fim
